[program:haproxy]
command=haproxy -f /usr/local/etc/haproxy/haproxy.cfg -W -S /var/run/haproxy/admin.sock
directory=/
autostart=true
autorestart=true
startretries=3
user=haproxy
stdout_logfile=/var/log/supervisor/haproxy.log
stderr_logfile=/var/log/supervisor/haproxy_error.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_backups=10
# Handle HAProxy's preferred clean shutdown signal (SIGUSR1)
stopsignal=USR1
stopwaitsecs=30
killasgroup=true
stopasgroup=true